POST http://localhost:5000/api/auth/register_guest
Content-Type: application/json

{
    "email": "nam1@gmail.com",
    "password": "nam",
    "full_name": "Phan Phước Hải Nam",
    "phone_number": "0777777777",
    "address": "Sài Gòn",
    "birthday": "2003-11-31",
    "user_id": "123456789874"
}

###
POST http://localhost:5000/api/auth/register_staff
Content-Type: application/json

{
    "email": "minh@gmail.com",
    "password": "minh",
    "full_name": "Huỳnh Cao Minh",
    "phone_number": "0222222222",
    "address": "Củ Chi",
    "birthday": "2003-1-1",
    "user_id": "123456789874"
}


###
POST http://localhost:5000/api/auth/register_System_Admin
Content-Type: application/json

{
    "email": "system_admin@gmail.com",
    "password": "len",
    "full_name": "Bùi Tiến Lên",
    "phone_number": "066666666",
    "address": "Sài Gòn",
    "birthday": "1980-2-2",
    "user_id": "123456789874"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "toan@gmail.com",
    "password": "toan"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "thao@gmail.com",
    "password": "thao"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "system_admin@gmail.com",
    "password": "len"
}

###
GET http://localhost:5000/api/user/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTU3MzFlNWM2ZjQzMDZlYzQ1ZjY4OGMiLCJpYXQiOjE3MDEyMjE3Mjh9.zVYMbkWp7xs4njFy5ueusYCcb8W1wMYE8y-19vKR93w

###
GET http://localhost:5000/api/user/find_info/system_admin@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTU3MzQwYWM2ZjQzMDZlYzQ1ZjY4OWIiLCJpYXQiOjE3MDAyMTM3NzV9.Wrg2gLrQU4RypNlEnbGOUeKF7K0Q5acJQysIE-ZpfWc

###
GET http://localhost:5000/api/user/get_guest_list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTU3MzQwYWM2ZjQzMDZlYzQ1ZjY4OWIiLCJpYXQiOjE3MDAyMTc4Mjh9.DiDAm1JomSQM2oyjSwBGViEpwCnyqvLbRxXEvZ7qJk4
###
GET http://localhost:5000/api/user/get_staff_list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTU3Mzk4MWM2ZjJkOWMxMWNlMmY5MGMiLCJpYXQiOjE3MDAyMTc4NzN9.PDZyYwtP7kddsT7tVCS6_mHyAN38BMhbdTFGe1cI1D4

###
PUT http://localhost:5000/api/user/user_info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTU3N2M0Y2FlZjkwZmM5ZDJlOWQ1MDIiLCJpYXQiOjE3MDAyMzI1NTJ9.3m87OFhOtf9cLcs08uxTsHjH-ZaBj5UUV8XBkVyZT9I

{
    "email": "nam@gmail.com",
    "password": "nam",
    "full_name": "Phan Phước Hải Nam",
    "phone_number": "0777777777",
    "address": "Sài Gòn",
    "birthday": "2003-11-31",
    "user_id": "123456789874"
}

###
DELETE http://localhost:5000/api/user/nam@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTU3MzQwYWM2ZjQzMDZlYzQ1ZjY4OWIiLCJpYXQiOjE3MDAyMzMyMzl9.I2MNWEFgN-fj48_lB_eTqbzbA6yycPuM21jfHm_3OFU

###
GET http://localhost:5000/api/room/info/102
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTU3MzFlNWM2ZjQzMDZlYzQ1ZjY4OGMiLCJpYXQiOjE3MDEyNjg2Mzd9.Md-mSsJA_T8tnyp5ygit9RmNrkZ8nXk8V6E6mGwnEXM

###
POST http://localhost:5000/api/room/add_room
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTU3MzFlNWM2ZjQzMDZlYzQ1ZjY4OGMiLCJpYXQiOjE3MDEyNjg2Mzd9.Md-mSsJA_T8tnyp5ygit9RmNrkZ8nXk8V6E6mGwnEXM

{
    "room_type": "Room5",
    "room_number": "105",
    "description": "Mô tả của phòng 5",
    "state": "true",
    "price": 500000,
    "discount": 10
}

###
PUT http://localhost:5000/api/room/update_room
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTU3Mzk4MWM2ZjJkOWMxMWNlMmY5MGMiLCJpYXQiOjE3MDAyMzU3NTl9.XZpq83J4k4ulgspajBalizw29hVKwJTJHnG5FIOVM3k
Content-Type: application/json

{
    "room_type": "Room5",
    "room_number": "104",
    "description": "Mô tả của phòng 5",
    "state": "true",
    "price": 500000,
    "discount": 10
}

###
DELETE http://localhost:5000/api/room/105
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTU3Mzk4MWM2ZjJkOWMxMWNlMmY5MGMiLCJpYXQiOjE3MDAyMzU3NTl9.XZpq83J4k4ulgspajBalizw29hVKwJTJHnG5FIOVM3k
Content-Type: application/json


###
POST http://localhost:5000/api/feedback
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTU3MzFlNWM2ZjQzMDZlYzQ1ZjY4OGMiLCJpYXQiOjE3MDExNzc2ODR9.TinI-Hyy_2H0n7b6ZV-nXAbsgz-ZDoqn-ICIkxcW3pU
Content-Type: application/json

{
    "description": "Mô tả của phòng 5",
    "rate": 5
}


###
GET http://localhost:5000/api/feedback
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTU3MzFlNWM2ZjQzMDZlYzQ1ZjY4OGMiLCJpYXQiOjE3MDExNzc2ODR9.TinI-Hyy_2H0n7b6ZV-nXAbsgz-ZDoqn-ICIkxcW3pU

###
DELETE http://localhost:5000/api/feedback/6565ec0e42ddfd195365f406
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTU3MzFlNWM2ZjQzMDZlYzQ1ZjY4OGMiLCJpYXQiOjE3MDExNzc2ODR9.TinI-Hyy_2H0n7b6ZV-nXAbsgz-ZDoqn-ICIkxcW3pU

###
PUT http://localhost:5000/api/feedback/6565e9c0753f4d9ec90f0a94
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTU3MzFlNWM2ZjQzMDZlYzQ1ZjY4OGMiLCJpYXQiOjE3MDExNzc2ODR9.TinI-Hyy_2H0n7b6ZV-nXAbsgz-ZDoqn-ICIkxcW3pU
Content-Type: application/json

{
    "description": "Phong xau vl",
    "rate": 5
}

###
POST http://localhost:5000/api/table/add_table
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTU3Mzk4MWM2ZjJkOWMxMWNlMmY5MGMiLCJpYXQiOjE3MDExODE4OTF9.s7weV8dmRi9Le-KX2ZE0NiggYw1W8dygbWx4E7Fo3BE
Content-Type: application/json

{
    "table_type": "Table1",
    "table_number": "1",
    "state": "true",
    "price": 500000
}

###
PUT http://localhost:5000/api/table/update_table
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTU3Mzk4MWM2ZjJkOWMxMWNlMmY5MGMiLCJpYXQiOjE3MDExODE4OTF9.s7weV8dmRi9Le-KX2ZE0NiggYw1W8dygbWx4E7Fo3BE
Content-Type: application/json

{
    "table_type": "Table1",
    "table_number": "1",
    "state": "true",
    "price": 555000
}

###
DELETE http://localhost:5000/api/table/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTU3Mzk4MWM2ZjJkOWMxMWNlMmY5MGMiLCJpYXQiOjE3MDExODE4OTF9.s7weV8dmRi9Le-KX2ZE0NiggYw1W8dygbWx4E7Fo3BE

###
Get http://localhost:5000/api/table/info/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTY5MzY1MmMzZWRjMjllMjg3MWE5OTEiLCJpYXQiOjE3MDE0MjQwODZ9.kMPk31o0TmS8vbXFOSnQVT18JpDmGybv0Z3Dr8IqtLo


###
POST http://localhost:5000/api/dish/add_dish
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTY5MzY1MmMzZWRjMjllMjg3MWE5OTEiLCJpYXQiOjE3MDE0MTY3ODh9.yR_jO2EB-pOz8A_49nNoZy0O5rUiHkuC_Qr97rR0NX4
Content-Type: application/json

{
    "dish_name": "Steak",
    "description": "Bò bít tết",
    "state": "true",
    "price": 100000,
    "discount": 10
}

###
PUT http://localhost:5000/api/dish/update_dish
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTY5MzY1MmMzZWRjMjllMjg3MWE5OTEiLCJpYXQiOjE3MDE0MTczNDF9.Rii_Ojk1GngXD3oIOT2Pzfoa0sSBMYT9B9WE_qtKEsY
Content-Type: application/json

{
    "dish_name": "Lobster",
    "description": "Tôm hùm 2",
    "state": "true",
    "price": 5000000,
    "discount": 10
}

###
DELETE http://localhost:5000/api/dish/Lobster
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTY5MzY1MmMzZWRjMjllMjg3MWE5OTEiLCJpYXQiOjE3MDE0MTc4NDh9.QIHOAYsDV53S7KWjak-l1lZD23BIVO-LC2y5H78l_MU
Content-Type: application/json


###
GET http://localhost:5000/api/room/available_rooms
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTY5MzY1MmMzZWRjMjllMjg3MWE5OTEiLCJpYXQiOjE3MDE0MjMyOTd9.c96pkbeyFN4WmAtg_Tj83brc2q9Nku6gawUYwnVHDbs

###
GET http://localhost:5000/api/table/available_tables
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTY5MzY1MmMzZWRjMjllMjg3MWE5OTEiLCJpYXQiOjE3MDE0MjMyOTd9.c96pkbeyFN4WmAtg_Tj83brc2q9Nku6gawUYwnVHDbs