POST http://localhost:5000/api/auth/register_staff
Content-Type: application/json

{
    "username": "toan",
    "password": "toan"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "toan",
    "password": "toan"
}